// @ts-nocheck
import * as __fd_glob_69 from "../content/docs/reference/kernel-spec/implementation/patterns/tap.mdx?collection=docs"
import * as __fd_glob_68 from "../content/docs/reference/kernel-spec/testing/workflow.mdx?collection=docs"
import * as __fd_glob_67 from "../content/docs/reference/kernel-spec/testing/validation.mdx?collection=docs"
import * as __fd_glob_66 from "../content/docs/reference/kernel-spec/testing/testing-protocol.mdx?collection=docs"
import * as __fd_glob_65 from "../content/docs/reference/kernel-spec/testing/test-spec-template.mdx?collection=docs"
import * as __fd_glob_64 from "../content/docs/reference/kernel-spec/testing/index.mdx?collection=docs"
import * as __fd_glob_63 from "../content/docs/reference/kernel-spec/spec/hub.mdx?collection=docs"
import * as __fd_glob_62 from "../content/docs/reference/kernel-spec/spec/harness.mdx?collection=docs"
import * as __fd_glob_61 from "../content/docs/reference/kernel-spec/spec/flow-runtime.mdx?collection=docs"
import * as __fd_glob_60 from "../content/docs/reference/kernel-spec/spec/events.mdx?collection=docs"
import * as __fd_glob_59 from "../content/docs/reference/kernel-spec/spec/channel.mdx?collection=docs"
import * as __fd_glob_58 from "../content/docs/reference/kernel-spec/spec/agent.mdx?collection=docs"
import * as __fd_glob_57 from "../content/docs/reference/kernel-spec/reference/protocol-types.mdx?collection=docs"
import * as __fd_glob_56 from "../content/docs/reference/kernel-spec/implementation/traceability.mdx?collection=docs"
import * as __fd_glob_55 from "../content/docs/reference/kernel-spec/implementation/roadmap.mdx?collection=docs"
import * as __fd_glob_54 from "../content/docs/reference/kernel-spec/implementation/index.mdx?collection=docs"
import * as __fd_glob_53 from "../content/docs/reference/kernel-spec/implementation/conformance.mdx?collection=docs"
import * as __fd_glob_52 from "../content/docs/reference/kernel-spec/flow/when.mdx?collection=docs"
import * as __fd_glob_51 from "../content/docs/reference/kernel-spec/flow/registry.mdx?collection=docs"
import * as __fd_glob_50 from "../content/docs/reference/kernel-spec/flow/node-catalog.mdx?collection=docs"
import * as __fd_glob_49 from "../content/docs/reference/kernel-spec/flow/flow-spec.mdx?collection=docs"
import * as __fd_glob_48 from "../content/docs/reference/kernel-spec/flow/execution.mdx?collection=docs"
import * as __fd_glob_47 from "../content/docs/reference/kernel-spec/flow/edge-routing.mdx?collection=docs"
import * as __fd_glob_46 from "../content/docs/reference/kernel-spec/flow/bindings.mdx?collection=docs"
import * as __fd_glob_45 from "../content/docs/reference/kernel-spec/decisions/0003-bindings-a3.mdx?collection=docs"
import * as __fd_glob_44 from "../content/docs/reference/kernel-spec/decisions/0002-edges-required.mdx?collection=docs"
import * as __fd_glob_43 from "../content/docs/reference/kernel-spec/decisions/0001-naming-flow-vs-workflow.mdx?collection=docs"
import * as __fd_glob_42 from "../content/docs/reference/kernel-spec/index.mdx?collection=docs"
import * as __fd_glob_41 from "../content/docs/reference/api/index.mdx?collection=docs"
import * as __fd_glob_40 from "../content/docs/reference/api/hub.mdx?collection=docs"
import * as __fd_glob_39 from "../content/docs/reference/api/flow-runtime.mdx?collection=docs"
import * as __fd_glob_38 from "../content/docs/reference/api/events.mdx?collection=docs"
import * as __fd_glob_37 from "../content/docs/reference/api/channel.mdx?collection=docs"
import * as __fd_glob_36 from "../content/docs/reference/api/agent.mdx?collection=docs"
import * as __fd_glob_35 from "../content/docs/reference/index.mdx?collection=docs"
import * as __fd_glob_34 from "../content/docs/learn/when-policy.mdx?collection=docs"
import * as __fd_glob_33 from "../content/docs/learn/index.mdx?collection=docs"
import * as __fd_glob_32 from "../content/docs/learn/flow-inputs.mdx?collection=docs"
import * as __fd_glob_31 from "../content/docs/learn/first-flow.mdx?collection=docs"
import * as __fd_glob_30 from "../content/docs/learn/custom-node.mdx?collection=docs"
import * as __fd_glob_29 from "../content/docs/learn/channels.mdx?collection=docs"
import * as __fd_glob_28 from "../content/docs/learn/bindings-a3.mdx?collection=docs"
import * as __fd_glob_27 from "../content/docs/guides/write-replay-tests.mdx?collection=docs"
import * as __fd_glob_26 from "../content/docs/guides/testing-workflow.mdx?collection=docs"
import * as __fd_glob_25 from "../content/docs/guides/record-and-promote-fixtures.mdx?collection=docs"
import * as __fd_glob_24 from "../content/docs/guides/index.mdx?collection=docs"
import * as __fd_glob_23 from "../content/docs/guides/faq.mdx?collection=docs"
import * as __fd_glob_22 from "../content/docs/guides/debugging.mdx?collection=docs"
import * as __fd_glob_21 from "../content/docs/concepts/kernel-vs-flow.mdx?collection=docs"
import * as __fd_glob_20 from "../content/docs/concepts/index.mdx?collection=docs"
import * as __fd_glob_19 from "../content/docs/concepts/graph.mdx?collection=docs"
import * as __fd_glob_18 from "../content/docs/concepts/event-model.mdx?collection=docs"
import * as __fd_glob_17 from "../content/docs/concepts/conformance-model.mdx?collection=docs"
import * as __fd_glob_16 from "../content/docs/concepts/architecture-overview.mdx?collection=docs"
import * as __fd_glob_15 from "../content/docs/test.mdx?collection=docs"
import * as __fd_glob_14 from "../content/docs/index.mdx?collection=docs"
import { default as __fd_glob_13 } from "../content/docs/reference/kernel-spec/implementation/patterns/meta.json?collection=docs"
import { default as __fd_glob_12 } from "../content/docs/reference/kernel-spec/testing/meta.json?collection=docs"
import { default as __fd_glob_11 } from "../content/docs/reference/kernel-spec/flow/meta.json?collection=docs"
import { default as __fd_glob_10 } from "../content/docs/reference/kernel-spec/spec/meta.json?collection=docs"
import { default as __fd_glob_9 } from "../content/docs/reference/kernel-spec/reference/meta.json?collection=docs"
import { default as __fd_glob_8 } from "../content/docs/reference/kernel-spec/implementation/meta.json?collection=docs"
import { default as __fd_glob_7 } from "../content/docs/reference/kernel-spec/decisions/meta.json?collection=docs"
import { default as __fd_glob_6 } from "../content/docs/reference/kernel-spec/meta.json?collection=docs"
import { default as __fd_glob_5 } from "../content/docs/reference/api/meta.json?collection=docs"
import { default as __fd_glob_4 } from "../content/docs/reference/meta.json?collection=docs"
import { default as __fd_glob_3 } from "../content/docs/learn/meta.json?collection=docs"
import { default as __fd_glob_2 } from "../content/docs/guides/meta.json?collection=docs"
import { default as __fd_glob_1 } from "../content/docs/concepts/meta.json?collection=docs"
import { default as __fd_glob_0 } from "../content/docs/meta.json?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const docs = await create.docs("docs", "content/docs", {"meta.json": __fd_glob_0, "concepts/meta.json": __fd_glob_1, "guides/meta.json": __fd_glob_2, "learn/meta.json": __fd_glob_3, "reference/meta.json": __fd_glob_4, "reference/api/meta.json": __fd_glob_5, "reference/kernel-spec/meta.json": __fd_glob_6, "reference/kernel-spec/decisions/meta.json": __fd_glob_7, "reference/kernel-spec/implementation/meta.json": __fd_glob_8, "reference/kernel-spec/reference/meta.json": __fd_glob_9, "reference/kernel-spec/spec/meta.json": __fd_glob_10, "reference/kernel-spec/flow/meta.json": __fd_glob_11, "reference/kernel-spec/testing/meta.json": __fd_glob_12, "reference/kernel-spec/implementation/patterns/meta.json": __fd_glob_13, }, {"index.mdx": __fd_glob_14, "test.mdx": __fd_glob_15, "concepts/architecture-overview.mdx": __fd_glob_16, "concepts/conformance-model.mdx": __fd_glob_17, "concepts/event-model.mdx": __fd_glob_18, "concepts/graph.mdx": __fd_glob_19, "concepts/index.mdx": __fd_glob_20, "concepts/kernel-vs-flow.mdx": __fd_glob_21, "guides/debugging.mdx": __fd_glob_22, "guides/faq.mdx": __fd_glob_23, "guides/index.mdx": __fd_glob_24, "guides/record-and-promote-fixtures.mdx": __fd_glob_25, "guides/testing-workflow.mdx": __fd_glob_26, "guides/write-replay-tests.mdx": __fd_glob_27, "learn/bindings-a3.mdx": __fd_glob_28, "learn/channels.mdx": __fd_glob_29, "learn/custom-node.mdx": __fd_glob_30, "learn/first-flow.mdx": __fd_glob_31, "learn/flow-inputs.mdx": __fd_glob_32, "learn/index.mdx": __fd_glob_33, "learn/when-policy.mdx": __fd_glob_34, "reference/index.mdx": __fd_glob_35, "reference/api/agent.mdx": __fd_glob_36, "reference/api/channel.mdx": __fd_glob_37, "reference/api/events.mdx": __fd_glob_38, "reference/api/flow-runtime.mdx": __fd_glob_39, "reference/api/hub.mdx": __fd_glob_40, "reference/api/index.mdx": __fd_glob_41, "reference/kernel-spec/index.mdx": __fd_glob_42, "reference/kernel-spec/decisions/0001-naming-flow-vs-workflow.mdx": __fd_glob_43, "reference/kernel-spec/decisions/0002-edges-required.mdx": __fd_glob_44, "reference/kernel-spec/decisions/0003-bindings-a3.mdx": __fd_glob_45, "reference/kernel-spec/flow/bindings.mdx": __fd_glob_46, "reference/kernel-spec/flow/edge-routing.mdx": __fd_glob_47, "reference/kernel-spec/flow/execution.mdx": __fd_glob_48, "reference/kernel-spec/flow/flow-spec.mdx": __fd_glob_49, "reference/kernel-spec/flow/node-catalog.mdx": __fd_glob_50, "reference/kernel-spec/flow/registry.mdx": __fd_glob_51, "reference/kernel-spec/flow/when.mdx": __fd_glob_52, "reference/kernel-spec/implementation/conformance.mdx": __fd_glob_53, "reference/kernel-spec/implementation/index.mdx": __fd_glob_54, "reference/kernel-spec/implementation/roadmap.mdx": __fd_glob_55, "reference/kernel-spec/implementation/traceability.mdx": __fd_glob_56, "reference/kernel-spec/reference/protocol-types.mdx": __fd_glob_57, "reference/kernel-spec/spec/agent.mdx": __fd_glob_58, "reference/kernel-spec/spec/channel.mdx": __fd_glob_59, "reference/kernel-spec/spec/events.mdx": __fd_glob_60, "reference/kernel-spec/spec/flow-runtime.mdx": __fd_glob_61, "reference/kernel-spec/spec/harness.mdx": __fd_glob_62, "reference/kernel-spec/spec/hub.mdx": __fd_glob_63, "reference/kernel-spec/testing/index.mdx": __fd_glob_64, "reference/kernel-spec/testing/test-spec-template.mdx": __fd_glob_65, "reference/kernel-spec/testing/testing-protocol.mdx": __fd_glob_66, "reference/kernel-spec/testing/validation.mdx": __fd_glob_67, "reference/kernel-spec/testing/workflow.mdx": __fd_glob_68, "reference/kernel-spec/implementation/patterns/tap.mdx": __fd_glob_69, });